# Generated by Django 5.1.1 on 2024-09-30 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='quantity',
            new_name='purchase_quantity',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='quantity',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_revenue',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.supplier'),
        ),
    ]
